language: php

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer --version
  - wget http://www.phing.info/get/phing-latest.phar

script: php phing-latest.phar
