<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AcAssets\Service\Factory\AssetsServiceFactory' => __DIR__ . '/src/AcAssets/Service/Factory/AssetsServiceFactory.php',
  'AcAssets\Service\AssetsService'                => __DIR__ . '/src/AcAssets/Service/AssetsService.php',
  'AcAssets\Service\AssetsServiceInterface'       => __DIR__ . '/src/AcAssets/Service/AssetsServiceInterface.php',
  'AcAssets\Options\CssOptions'                   => __DIR__ . '/src/AcAssets/Options/CssOptions.php',
  'AcAssets\Options\Factory\AssetsOptionsFactory' => __DIR__ . '/src/AcAssets/Options/Factory/AssetsOptionsFactory.php',
  'AcAssets\Options\AssetsOptions'                => __DIR__ . '/src/AcAssets/Options/AssetsOptions.php',
  'AcAssets\Options\JsOptions'                    => __DIR__ . '/src/AcAssets/Options/JsOptions.php',
  'AcAssets\Module'                               => __DIR__ . '/Module.php',
);
